# numpy 연산


+ abx / fabs : 절대값
+ sqrt	: 제곱근
+ square	: 제곱
+ exp	 : 지수
+ ceil / floor : 소수자릿수 올림/내림
+ rint	:소수자릿수 반올림
+ modf	: 원소의 몫과 나머지를 각 배열로 변환
+ lsnan	: 각 원소가 Nan인지 아닌지 불린 배열로 리턴

+ add / subtract	: 두 배열의 같은 위치의 요소끼리 덧셈/뺄셈
+ multiply	: 배열 원소끼리 곱셉
+ divide	: 첫번째 배열의 원소에서 두번째 배열 원소로 나눔
+ power	: 첫번째 배열의 원소에 두번째 배열의 원소만큼 제곱
+ maximum	: 비교하는 두 원소 중 큰 값
+ mod	: 첫번째 배열의 원소에서 두번째 배열 원소로 나눈 나머지



###  선형대수 연산

In [3]:
import numpy as np

# (1) 배열의 연산
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,1,1],[2,2,2]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)   # [주의] 행렬의 곱이 아님
print(arr1 / 4)


[[2 3 4]
 [6 7 8]]
[[0 1 2]
 [2 3 4]]
[[ 1  2  3]
 [ 8 10 12]]
[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]


In [4]:
# (2) 행렬의 곱

A = np.array(
    [[1, 2, 3],
    [4, 5, 6]])
B = np.array(
    [[7,8],
     [9,10],
     [11, 12]])

print('행렬의 곱 :\n',np.dot(A,B))

행렬의 곱 :
 [[ 58  64]
 [139 154]]


In [5]:
# (3) 전치행렬
#       - 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
A = np.array(
    [[1, 2, 3],
    [4, 5, 6]])
A2 = np.transpose(A)
print('A의 전치행렬: \n', A2)


A의 전치행렬: 
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
### 넘파이 통계 함수

+ sum	: 배열 원소들의 합
+ mean :산술 평균
+ std / var	: 표준편차 / 분산
+ min / max	: 최소 값 / 최대 값
+ cumsum	: 각 원소의 누적값
+ cumprod	: 각 원소의 누적곱


In [14]:
import numpy as np

ar = np.array([1,3,5,7])

In [15]:
# 평균
print(np.mean(ar))

4.0


In [16]:
# 총합
np.sum(ar)

16

In [17]:
# 큰값
np.max(ar)

7

In [18]:
# 제곱의 합 (각 원소의 누적합)
np.cumsum(ar)

array([ 1,  4,  9, 16], dtype=int32)

#### 2차원 배열에서

In [12]:
# 2차원 배열을 arr 생성
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 총합
np.sum(arr)

np.sum(arr[1])   #  특정 행의 합

np.sum(arr, axis=0) # axis=0 : 행방향 - 열단위 합  ** 헷갈린다

np.sum(arr, axis=1) # axis=1 : 열방향 - 행단위 합

array([ 6, 15])

In [25]:
# 불린 배열에서의 배열
arr2 = np.array([[12, 7, 22],[20,33, 44], [4,5,6]])
arr2[arr2>20]

#arr2>20).sum()  # 결과- 3
# arr2[arr2>20].sum() # 22+33+44



SyntaxError: invalid syntax (<ipython-input-25-75805b1feace>, line 5)

In [26]:
# unique 연산자를 이용하여 중복제거
region = np.array(['가산','서울','서울','판교','가산'])
np.unique(region)

array(['가산', '서울', '판교'], dtype='<U2')

### 행렬의 정렬 

In [38]:
arr = np.array([9,3,6,1,7,2,4,8,5,6])
np.sort(arr)
np.sort(arr[::-1]) # 내림차순


SyntaxError: invalid syntax (<ipython-input-38-be8d4fbd3227>, line 3)

In [37]:
arr2 = np.array([[9,3,6],[1,7,2],[4,8,5]])
np.sort(arr2)
np.sort(arr2, axis=1)
np.sort(arr2, axis=0)   # 열단위 정렬 -> [주의] 다른 행간의 성분들이 섞인다


array([[1, 3, 2],
       [4, 7, 5],
       [9, 8, 6]])